
name: Schedule job

on:
  push:
    branches:
      - schedule
  # https://crontab.guru/examples.html
  # UCT +8: 10.30 (+- 20min) am
  schedule:
    # - cron: '30 2 * * *'
    - cron: '*/2 * * * *'

jobs:
  build-and-schedule:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    
    - name: Schedule job
      env:
        jbsk: ${{ secrets.JSON_BIN_SECRET_KEY }}
        bid: ${{ secrets.BUSINESS_BIN_ID }}
      run: npm install -g pnpm && pnpm install --registry=https://registry.npm.taobao.org && pnpm run schedule